nelmio_api_doc:
    models:
        names:
            - { alias: CreateClientInputData, type: App\Application\Client\Create\CreateClientInputData }
            - { alias: LoginInputData, type: App\Infrastructure\Doc\LoginInputData }
            - { alias: LoginOutputData, type: App\Infrastructure\Doc\LoginOutputData }
            - { alias: Client, type: App\Infrastructure\Persistence\Entity\Client }
            - { alias: FindAllClientOutPutData, type: App\Application\Client\FindAll\FindAllClientOutPutData }

            - { alias: CreateProductInputData, type: App\Application\Product\Create\CreateProductInputData }
            - { alias: ProductOutputData, type: App\Application\Product\Create\ProductOutputData }
            - { alias: UpdateProductInputData, type: App\Application\Product\Update\UpdateProductInputData }
            - { alias: FindAllProductsOutputData, type: App\Application\Product\FindAll\FindAllProductsOutputData }
            - { alias: FavoriteProductsListOfClientInputData, type: App\Application\FavoriteProductsListOfClient\Add\FavoriteProductsListOfClientInputData }
            - { alias: ProductReviewInputData, type: App\Application\ProductReview\ProductReviewInputData }
    documentation:
        info:
            title: Clean architecture api
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
