version: '3'

services:
    app:
        build: .
        container_name: clean-architecture-api
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - database

    nginx:
        build: docker/nginx
        container_name: clean-architecture-api-nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    database:
        build: docker/mysql
        container_name: clean-architecture-api-database
        ports:
            - "3306:3306"
        volumes:
            - clean_mysql:/var/lib/mysql
            - ./docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=clean_ecomerce
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    clean_mysql:
        driver: local
